"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";

export type FundPoint = { date: string; value: number; daily_return_pct?: number | null; ma20?: number | null; ma60?: number | null; ma120?: number | null; volume?: number | null };
const ranges = { "1月": 22, "3月": 66, "6月": 126, "1年": 252, "3年": 756, "全部": Infinity } as const;
type Range = keyof typeof ranges;
const fmt = (value: number | null | undefined) => value == null ? "—" : value.toLocaleString("zh-CN", { maximumFractionDigits: 3 });
const pct = (value: number | null | undefined) => value == null ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const tone = (value: number | null | undefined) => value == null || value === 0 ? "neutral" : value > 0 ? "positive" : "negative";
const sample = <T,>(rows: T[], maximum: number) => { const step = Math.max(1, Math.ceil(rows.length / maximum)); const output = rows.map((row, index) => ({ row, index })).filter(({ index }) => index % step === 0); if (output.at(-1)?.index !== rows.length - 1) output.push({ row: rows.at(-1)!, index: rows.length - 1 }); return output; };

function Canvas({ points, color, log, lockedDate, onLockDate, large }: { points: FundPoint[]; color: string; log: boolean; lockedDate: string | null; onLockDate: (date: string) => void; large?: boolean }) {
  const ref = useRef<HTMLCanvasElement>(null), [hover, setHover] = useState<number | null>(null);
  const locked = lockedDate ? points.reduce((best, point, index) => Math.abs(Date.parse(point.date) - Date.parse(lockedDate)) < Math.abs(Date.parse(points[best].date) - Date.parse(lockedDate)) ? index : best, 0) : null;
  const active = hover ?? locked;
  useEffect(() => { const canvas = ref.current; if (!canvas || points.length < 2) return; const draw = () => { const box = canvas.getBoundingClientRect(), ratio = devicePixelRatio || 1; canvas.width = box.width * ratio; canvas.height = box.height * ratio; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.setTransform(ratio,0,0,ratio,0,0); const width = box.width, height = box.height, bottom = 26, top = 12, volume = points.some((p) => p.volume) ? 36 : 0, plotH = height-top-bottom-volume, values = points.flatMap((p) => [p.value,p.ma20,p.ma60,p.ma120]).filter((v):v is number=>v!=null&&(!log||v>0)), transformed=values.map((v)=>log?Math.log(v):v), low=Math.min(...transformed), high=Math.max(...transformed), spread=high-low||1, x=(i:number)=>i/(points.length-1)*width, y=(v:number)=>top+(1-((log?Math.log(v):v)-low)/spread)*plotH, drawing=sample(points,Math.max(120,Math.floor(width*2))); if (volume) { const maxVolume=Math.max(...points.map((p)=>p.volume??0),1); drawing.forEach(({row,index})=>{if(!row.volume)return; const bar=row.volume/maxVolume*(volume-5); ctx.fillStyle=(row.daily_return_pct??0)>=0?"rgba(251,113,133,.25)":"rgba(52,211,153,.25)"; ctx.fillRect(x(index),height-bottom-bar,Math.max(1,width/drawing.length),bar);}); } const line=(key:"value"|"ma20"|"ma60"|"ma120",stroke:string,lineWidth:number)=>{ctx.beginPath();ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;let started=false;drawing.forEach(({row,index})=>{const value=row[key];if(value==null)return;if(!started){ctx.moveTo(x(index),y(value));started=true;}else ctx.lineTo(x(index),y(value));});ctx.stroke();}; line("ma120","rgba(245,158,11,.7)",1);line("ma60","rgba(167,139,250,.7)",1);line("ma20","rgba(148,163,184,.6)",1);line("value",color,2);ctx.font="9px ui-monospace";ctx.fillStyle="#66798c";ctx.fillText(points[0].date.slice(0,7),0,height-5);ctx.textAlign="right";ctx.fillText(points.at(-1)!.date.slice(0,7),width,height-5);if(active!=null){ctx.strokeStyle=hover==null?"rgba(34,211,238,.85)":"rgba(226,232,240,.55)";ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x(active),top);ctx.lineTo(x(active),height-bottom);ctx.stroke();ctx.setLineDash([]);} }; draw(); const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect(); },[active,color,hover,log,points]);
  const update=(event:ReactPointerEvent<HTMLCanvasElement>)=>{const box=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-box.left)/box.width));setHover(Math.round(ratio*(points.length-1)));};
  const point=active==null?null:points[active];
  return <div className={`fund-chart-canvas ${large?"large":""}`}><canvas ref={ref} onPointerLeave={()=>setHover(null)} onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);update(event);}} onPointerMove={update} onPointerUp={(event)=>{update(event);const box=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-box.left)/box.width));onLockDate(points[Math.round(ratio*(points.length-1))].date);}} aria-label="可拖动查看并锁定日期的净值或价格曲线" />{point&&<div className="fund-tooltip"><strong>{point.date}{hover==null&&lockedDate?" · 已锁定":""}</strong><span>数值 {fmt(point.value)}</span><span className={tone(point.daily_return_pct)}>涨跌 {pct(point.daily_return_pct)}</span>{point.volume!=null&&<span>成交量 {fmt(point.volume)}</span>}<span>MA20 / 60 / 120<br />{fmt(point.ma20)} / {fmt(point.ma60)} / {fmt(point.ma120)}</span></div>}</div>;
}

export default function FundChart({ series, color = "#22d3ee", lockedDate, onLockDate, storageKey }: { series: FundPoint[]; color?: string; lockedDate: string | null; onLockDate: (date: string) => void; storageKey: string }) {
  const [range,setRange]=useState<Range>("1年"),[log,setLog]=useState(false),[expanded,setExpanded]=useState(false);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(`fund-chart-${storageKey}`)??"{}");if(saved.range in ranges)setRange(saved.range);setLog(Boolean(saved.log));}catch{}},[storageKey]);
  useEffect(()=>{localStorage.setItem(`fund-chart-${storageKey}`,JSON.stringify({range,log}));},[log,range,storageKey]);
  const points=useMemo(()=>Number.isFinite(ranges[range])?series.slice(-ranges[range]):series,[range,series]);
  const controls=<div className="mini-controls"><div className="range-buttons">{(Object.keys(ranges) as Range[]).map((label)=><button key={label} className={range===label?"active":""} onClick={()=>setRange(label)}>{label}</button>)}</div><button className={log?"active":""} onClick={()=>setLog((value)=>!value)}>对数</button><button onClick={()=>setExpanded(true)}>放大</button></div>;
  return <>{controls}<Canvas points={points} color={color} log={log} lockedDate={lockedDate} onLockDate={onLockDate}/><div className="sector-legend"><span><i style={{background:color}}/>净值/价格</span><span><i/>MA20</span><span><i className="line50"/>MA60</span><span><i className="line200"/>MA120</span><span>红涨绿跌 · 虚线为锁定日期</span></div>{expanded&&<div className="chart-modal" role="dialog" aria-modal="true" onClick={()=>setExpanded(false)}><div className="chart-modal-card panel" onClick={(event)=>event.stopPropagation()}><div className="modal-head"><h2>放大曲线</h2><button onClick={()=>setExpanded(false)}>关闭</button></div>{controls}<Canvas points={points} color={color} log={log} lockedDate={lockedDate} onLockDate={onLockDate} large/></div></div>}</>;
}
