"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";

type Point = {
  date: string; close: number; daily_return_pct: number | null;
  ema20: number | null; ema50: number | null; ema200: number | null;
  amount_billion: number | null; amount_ratio20: number | null;
  estimated_inflow_billion: number | null; estimated_outflow_billion: number | null;
  estimated_net_flow_billion: number | null; money_flow_ratio_pct: number | null;
  estimated_net_flow_5_billion: number | null; estimated_net_flow_20_billion: number | null;
  money_flow_ratio_5_pct: number | null; money_flow_ratio_20_pct: number | null;
  flow_confidence_pct: number | null;
};
type Summary = Omit<Point, "date" | "daily_return_pct"> & {
  daily_return_pct: number | null; returns: Record<string, number | null>;
  rsi14: number | null; volatility20_pct: number | null; trend: string;
};
type Quality = { status: "official" | "cached"; age_days: number; has_amount: boolean; calendar: string; note: string };
type IndexData = {
  code: string; name: string; category: string; source: string; color: string;
  calendar?: string; start_date: string; latest_date: string; history_path?: string;
  quality?: Quality; summary: Summary; series: Point[];
};
type SectorData = { generated_at: string; latest_a_share_date: string; requested_start_date: string; indices: IndexData[] };
type Evidence = { code: string; name: string; metric: string; label: string; value: string | number | null };
type Analysis = {
  market_date: string; generated_at: string; source: string; model: string | null;
  status?: "ok" | "fallback"; error?: string | null; text: string; disclaimer: string;
  sections?: Record<string, string>; evidence?: Evidence[];
};

const chartRanges = { "1月": 22, "3月": 66, "6月": 126, "1年": 252, "3年": 756, "全部": Infinity } as const;
type ChartRange = keyof typeof chartRanges;
const sectionLabels: Record<string, string> = { today: "今日结构", rotation: "轮动观察", confirmation: "量价确认", risks: "风险提示", next: "下一交易日观察" };
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const assetPath = (path: string) => `${basePath}${path}${path.endsWith(".json") ? `?v=${Date.now()}` : ""}`;
const fmt = (value: number | null | undefined, digits = 2) => value == null ? "—" : value.toLocaleString("zh-CN", { maximumFractionDigits: digits });
const pct = (value: number | null | undefined) => value == null ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const tone = (value: number | null | undefined) => value == null || value === 0 ? "neutral" : value > 0 ? "positive" : "negative";
const flowText = (value: number | null | undefined) => value == null ? "暂无成交额口径" : `${value >= 0 ? "净流入估算" : "净流出估算"} ${fmt(Math.abs(value))}亿元`;
const qualityOf = (item: IndexData): Quality => item.quality ?? { status: "cached", age_days: 0, has_amount: item.summary.amount_billion != null, calendar: item.calendar ?? "旧版数据", note: "等待新数据契约" };
const nearest = <T extends { date: string }>(points: T[], date: string) => points.reduce((best, point) => Math.abs(Date.parse(point.date) - Date.parse(date)) < Math.abs(Date.parse(best.date) - Date.parse(date)) ? point : best);
const periodReturn = (points: Point[], point: Point, sessions: number) => {
  const index = points.indexOf(point), base = points[Math.max(0, index - sessions)]?.close;
  return base ? (point.close / base - 1) * 100 : null;
};
const sampled = <T,>(items: T[], maximum: number) => {
  if (items.length <= maximum) return items.map((item, index) => ({ item, index }));
  const step = Math.ceil(items.length / maximum), output = items.map((item, index) => ({ item, index })).filter(({ index }) => index % step === 0);
  if (output.at(-1)?.index !== items.length - 1) output.push({ item: items.at(-1)!, index: items.length - 1 });
  return output;
};

function setupCanvas(canvas: HTMLCanvasElement) {
  const bounds = canvas.getBoundingClientRect(), ratio = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.floor(bounds.width * ratio)); canvas.height = Math.max(1, Math.floor(bounds.height * ratio));
  const context = canvas.getContext("2d"); context?.setTransform(ratio, 0, 0, ratio, 0, 0);
  return { context, width: bounds.width, height: bounds.height };
}

function IndexChartCanvas({ index, points, logScale, large = false, lockedDate, onLockDate }: {
  index: IndexData; points: Point[]; logScale: boolean; large?: boolean; lockedDate: string | null; onLockDate: (date: string) => void;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null), [hover, setHover] = useState<Point | null>(null);
  const active = hover ?? (lockedDate && points.length ? nearest(points, lockedDate) : null);
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas || points.length < 2) return;
    const draw = () => {
      const { context: ctx, width, height } = setupCanvas(canvas); if (!ctx) return;
      ctx.clearRect(0, 0, width, height);
      const top = 12, bottom = 24, volumeHeight = 38, priceHeight = height - top - bottom - volumeHeight;
      const values = points.flatMap((p) => [p.close, p.ema20, p.ema50, p.ema200]).filter((v): v is number => v != null && (!logScale || v > 0));
      const transformed = values.map((value) => logScale ? Math.log(value) : value), min = Math.min(...transformed), max = Math.max(...transformed), spread = max - min || 1;
      const x = (i: number) => (i / (points.length - 1)) * width;
      const y = (v: number) => top + priceHeight * (1 - ((logScale ? Math.log(v) : v) - min) / spread);
      const amountMax = Math.max(...points.map((p) => p.amount_billion ?? 0), 1), drawing = sampled(points, Math.max(120, Math.floor(width * 2)));
      drawing.forEach(({ item: point, index: i }) => { if (!point.amount_billion) return; const bar = point.amount_billion / amountMax * (volumeHeight - 7); ctx.fillStyle = (point.money_flow_ratio_pct ?? 0) < 0 ? "rgba(52,211,153,.25)" : "rgba(251,113,133,.25)"; ctx.fillRect(x(i), height - bottom - bar, Math.max(1, width / drawing.length), bar); });
      const line = (key: "close" | "ema20" | "ema50" | "ema200", color: string, lineWidth: number) => { ctx.beginPath(); ctx.strokeStyle = color; ctx.lineWidth = lineWidth; drawing.forEach(({ item, index }, i) => { const value = item[key]; if (value == null) return; i ? ctx.lineTo(x(index), y(value)) : ctx.moveTo(x(index), y(value)); }); ctx.stroke(); };
      line("ema200", "rgba(245,158,11,.7)", 1); line("ema50", "rgba(167,139,250,.7)", 1); line("ema20", "rgba(148,163,184,.55)", 1); line("close", index.color, 2);
      ctx.fillStyle = "#66798c"; ctx.font = "9px ui-monospace"; ctx.fillText(points[0].date.slice(0, 7), 0, height - 5); ctx.textAlign = "right"; ctx.fillText(points.at(-1)!.date.slice(0, 7), width, height - 5);
      if (active) { const i = points.indexOf(active); ctx.strokeStyle = lockedDate && !hover ? "rgba(34,211,238,.8)" : "rgba(226,232,240,.55)"; ctx.setLineDash([3, 3]); ctx.beginPath(); ctx.moveTo(x(i), top); ctx.lineTo(x(i), height - bottom); ctx.stroke(); ctx.setLineDash([]); }
    };
    draw(); const observer = new ResizeObserver(draw); observer.observe(canvas); return () => observer.disconnect();
  }, [active, index.color, lockedDate, logScale, points]);
  const update = (event: ReactPointerEvent<HTMLCanvasElement>) => { const box = event.currentTarget.getBoundingClientRect(), ratio = Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)); setHover(points[Math.round(ratio * (points.length - 1))]); };
  return <div className={`sector-mini-chart ${large ? "large" : ""}`}>
    <canvas ref={canvasRef} aria-label={`${index.name}价格、均线、成交额与资金方向估算图`} onPointerLeave={() => setHover(null)} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); update(event); }} onPointerMove={update} onPointerUp={(event) => { update(event); const box = event.currentTarget.getBoundingClientRect(), ratio = Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)); onLockDate(points[Math.round(ratio * (points.length - 1))].date); }} />
    {active && <div className="sector-tooltip"><strong>{active.date}{lockedDate && !hover ? " · 已锁定" : ""}</strong><span>收盘 {fmt(active.close)} · 当日 <b className={tone(active.daily_return_pct)}>{pct(active.daily_return_pct)}</b></span><span>5日 / 20日涨跌 <b className={tone(periodReturn(points, active, 5))}>{pct(periodReturn(points, active, 5))}</b> / <b className={tone(periodReturn(points, active, 20))}>{pct(periodReturn(points, active, 20))}</b></span><span>成交额 {active.amount_billion == null ? "—" : `${fmt(active.amount_billion)}亿元`}</span><span className={tone(active.estimated_net_flow_billion)}>{flowText(active.estimated_net_flow_billion)} · {pct(active.money_flow_ratio_pct)}</span><span>5日 / 20日净额估算<br />{fmt(active.estimated_net_flow_5_billion)} / {fmt(active.estimated_net_flow_20_billion)} 亿元</span><span>方向可信度 {pct(active.flow_confidence_pct)}</span><span>EMA20 / 50 / 200<br />{fmt(active.ema20)} / {fmt(active.ema50)} / {fmt(active.ema200)}</span></div>}
  </div>;
}

function ChartLegend({ color }: { color: string }) { return <div className="sector-legend"><span><i style={{ background: color }} />指数收盘</span><span><i className="line20" />EMA20</span><span><i className="line50" />EMA50</span><span><i className="line200" />EMA200</span><span><i className="volume" />成交额柱（红涨/流入，绿跌/流出）</span><span>虚线＝当前/锁定日期</span></div>; }

function MiniChart({ index, lockedDate, onLockDate, onNeedFull, loading }: { index: IndexData; lockedDate: string | null; onLockDate: (date: string) => void; onNeedFull: () => void; loading: boolean }) {
  const [range, setRange] = useState<ChartRange>("1年"), [logScale, setLogScale] = useState(false), [expanded, setExpanded] = useState(false), hydrated = useRef(false);
  useEffect(() => { const saved = localStorage.getItem(`sector-chart-${index.code}`); if (saved) { try { const value = JSON.parse(saved); if (value.range in chartRanges) setRange(value.range); setLogScale(Boolean(value.logScale)); } catch {} } hydrated.current = true; }, [index.code]);
  useEffect(() => { if (hydrated.current) localStorage.setItem(`sector-chart-${index.code}`, JSON.stringify({ range, logScale })); }, [index.code, logScale, range]);
  useEffect(() => { if (chartRanges[range] > index.series.length && index.start_date < index.series[0]?.date) onNeedFull(); }, [index.series, index.start_date, onNeedFull, range]);
  const points = useMemo(() => Number.isFinite(chartRanges[range]) ? index.series.slice(-chartRanges[range]) : index.series, [index.series, range]);
  const controls = <div className="mini-controls"><div className="range-buttons">{(Object.keys(chartRanges) as ChartRange[]).map((label) => <button className={range === label ? "active" : ""} key={label} onClick={() => setRange(label)}>{label}</button>)}</div><button className={logScale ? "active" : ""} onClick={() => setLogScale((v) => !v)}>对数</button><button onClick={() => setExpanded(true)}>放大</button>{loading && <small>载入历史…</small>}</div>;
  return <>{controls}<IndexChartCanvas index={index} points={points} logScale={logScale} lockedDate={lockedDate} onLockDate={onLockDate} /><ChartLegend color={index.color} /><a className="fund-entry" href={assetPath(`/funds.html?sector=${index.code}`)}>查看本板块持仓基金 →</a>
    {expanded && <div className="chart-modal" role="dialog" aria-modal="true" onClick={() => setExpanded(false)}><div className="chart-modal-card panel" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><span>{index.code} · {index.category}</span><h2>{index.name}</h2></div><button onClick={() => setExpanded(false)}>关闭</button></div>{controls}<IndexChartCanvas index={index} points={points} logScale={logScale} large lockedDate={lockedDate} onLockDate={onLockDate} /><ChartLegend color={index.color} /><p className="method-note">拖动连续查看，松手锁定日期并同步到所有图；成交额方向是量价位置估算，并非交易所披露净流入。</p></div></div>}
  </>;
}

function ComparisonChart({ indices, selected, requestedStart, logScale, lockedDate, onLockDate }: { indices: IndexData[]; selected: string[]; requestedStart: string; logScale: boolean; lockedDate: string | null; onLockDate: (date: string) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null), [hoverRatio, setHoverRatio] = useState<number | null>(null);
  const prepared = useMemo(() => { const chosen = indices.filter((item) => selected.includes(item.code)), starts = chosen.map((item) => item.series.find((p) => p.date >= requestedStart)?.date).filter(Boolean) as string[], commonStart = chosen.length && starts.length === chosen.length ? starts.sort().at(-1)! : requestedStart; return { commonStart, lines: chosen.map((item) => { const points = item.series.filter((p) => p.date >= commonStart), base = points[0]?.close; return { ...item, normalized: base ? points.map((point) => ({ ...point, value: (logScale ? Math.log(point.close / base) : point.close / base - 1) * 100 })) : [] }; }).filter((item) => item.normalized.length > 1) }; }, [indices, logScale, requestedStart, selected]);
  const bounds = useMemo(() => { if (!prepared.lines.length) return null; const first = Date.parse(prepared.commonStart), last = Math.max(...prepared.lines.flatMap((line) => line.normalized.map((p) => Date.parse(p.date)))); return { first, last }; }, [prepared]);
  const lockedRatio = lockedDate && bounds ? Math.max(0, Math.min(1, (Date.parse(lockedDate) - bounds.first) / Math.max(1, bounds.last - bounds.first))) : null, activeRatio = hoverRatio ?? lockedRatio;
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !prepared.lines.length || !bounds) return; const draw = () => { const { context: ctx, width, height } = setupCanvas(canvas); if (!ctx) return; ctx.clearRect(0, 0, width, height); const pad = { top: 20, right: 22, bottom: 32, left: 52 }, plotW = width - pad.left - pad.right, plotH = height - pad.top - pad.bottom, all = prepared.lines.flatMap((line) => line.normalized.map((p) => p.value)), min = Math.min(...all, 0), max = Math.max(...all, 0), margin = (max - min || 1) * .08, lo = min - margin, hi = max + margin, x = (date: string) => pad.left + (Date.parse(date) - bounds.first) / Math.max(1, bounds.last - bounds.first) * plotW, y = (value: number) => pad.top + (1 - (value - lo) / (hi - lo)) * plotH; ctx.font = "10px ui-monospace"; ctx.textAlign = "right"; ctx.textBaseline = "middle"; for (let i = 0; i <= 4; i++) { const value = hi - (hi - lo) * i / 4, py = y(value); ctx.strokeStyle = "rgba(148,163,184,.13)"; ctx.beginPath(); ctx.moveTo(pad.left, py); ctx.lineTo(width - pad.right, py); ctx.stroke(); ctx.fillStyle = "#66798c"; ctx.fillText(`${value.toFixed(0)}%`, pad.left - 8, py); } prepared.lines.forEach((line) => { ctx.strokeStyle = line.color; ctx.lineWidth = 1.8; ctx.beginPath(); sampled(line.normalized, Math.max(160, Math.floor(width * 2))).forEach(({ item }, i) => i ? ctx.lineTo(x(item.date), y(item.value)) : ctx.moveTo(x(item.date), y(item.value))); ctx.stroke(); }); ctx.textAlign = "center"; ctx.textBaseline = "top"; [0,.25,.5,.75,1].forEach((f) => { ctx.fillStyle = "#66798c"; ctx.fillText(new Date(bounds.first + (bounds.last - bounds.first) * f).toISOString().slice(0,7), 52 + plotW * f, height - 19); }); if (activeRatio != null) { const px = 52 + plotW * activeRatio; ctx.strokeStyle = hoverRatio == null ? "rgba(34,211,238,.8)" : "rgba(226,232,240,.5)"; ctx.setLineDash([3,3]); ctx.beginPath(); ctx.moveTo(px,20); ctx.lineTo(px,height-32); ctx.stroke(); ctx.setLineDash([]); } }; draw(); const observer = new ResizeObserver(draw); observer.observe(canvas); return () => observer.disconnect(); }, [activeRatio, bounds, hoverRatio, prepared]);
  const hovered = useMemo(() => activeRatio == null || !bounds ? null : prepared.lines.map((line) => ({ line, point: nearest(line.normalized, new Date(bounds.first + (bounds.last - bounds.first) * activeRatio).toISOString().slice(0,10)) })), [activeRatio, bounds, prepared]);
  const update = (event: ReactPointerEvent<HTMLCanvasElement>) => { const box = event.currentTarget.getBoundingClientRect(); setHoverRatio(Math.max(0, Math.min(1, (event.clientX - box.left - 52) / Math.max(1, box.width - 74)))); };
  return <><div className="comparison-chart"><canvas ref={canvasRef} aria-label="所选指数归一化涨跌幅比较图" onPointerLeave={() => setHoverRatio(null)} onPointerDown={(e) => { e.currentTarget.setPointerCapture(e.pointerId); update(e); }} onPointerMove={update} onPointerUp={(e) => { update(e); if (bounds) { const box = e.currentTarget.getBoundingClientRect(), ratio = Math.max(0,Math.min(1,(e.clientX-box.left-52)/Math.max(1,box.width-74))); onLockDate(new Date(bounds.first + (bounds.last-bounds.first)*ratio).toISOString().slice(0,10)); } }} />{hovered && <div className="comparison-tooltip"><strong>{hovered[0].point.date}{lockedDate && hoverRatio == null ? " · 已锁定" : ""}</strong>{hovered.map(({ line, point }) => <span key={line.code}><i style={{ background: line.color }} />{line.name}<b className={tone(point.value)}>{pct(point.value)}</b></span>)}</div>}</div><p className="method-note">彩色线＝所选指数；水平 0%＝共同起点；虚线＝当前/锁定日期。{logScale ? "对数收益适合长周期" : "普通累计涨跌幅"}，实际共同起点 {prepared.commonStart}。拖动查看，松手锁定并同步。</p></>;
}

export default function SectorsPage() {
  const [data, setData] = useState<SectorData | null>(null), [analysis, setAnalysis] = useState<Analysis | null>(null), [error, setError] = useState("");
  const [selected, setSelected] = useState<string[]>([]), [start, setStart] = useState(""), [comparisonLog, setComparisonLog] = useState(false), [lockedDate, setLockedDate] = useState<string | null>(null), [fullSeries, setFullSeries] = useState<Record<string, Point[]>>({}), [loading, setLoading] = useState<string[]>([]), [ready, setReady] = useState(false);
  const promises = useRef<Partial<Record<string, Promise<void>>>>({});
  useEffect(() => { Promise.all([fetch(assetPath("/data/sectors.json")).then((r) => r.json()), fetch(assetPath("/data/sector_analysis.json")).then((r) => r.json())]).then(([sectorData, analysisData]: [SectorData, Analysis]) => { setData(sectorData); setAnalysis(analysisData); const oneYear = new Date(`${sectorData.latest_a_share_date}T00:00:00`); oneYear.setFullYear(oneYear.getFullYear() - 1); let prefs: { selected?: string[]; start?: string; log?: boolean; date?: string | null } = {}; try { prefs = JSON.parse(localStorage.getItem("sector-dashboard-prefs") ?? "{}"); } catch {} const query = new URLSearchParams(location.search), querySelected = query.get("selected")?.split(",").filter(Boolean); setSelected(querySelected?.length ? querySelected : prefs.selected?.length ? prefs.selected : sectorData.indices.map((item) => item.code)); setStart(query.get("start") ?? prefs.start ?? oneYear.toISOString().slice(0,10)); setComparisonLog(query.has("log") ? query.get("log") === "1" : Boolean(prefs.log)); setLockedDate(query.get("date") ?? prefs.date ?? null); setReady(true); }).catch((reason) => setError(reason instanceof Error ? reason.message : "数据加载失败")); }, []);
  const loadFull = (item: IndexData) => { if (!item.history_path || fullSeries[item.code] || promises.current[item.code]) return; setLoading((v) => [...v, item.code]); promises.current[item.code] = fetch(assetPath(item.history_path)).then((r) => r.json()).then(({ series }) => setFullSeries((v) => ({ ...v, [item.code]: series }))).finally(() => setLoading((v) => v.filter((code) => code !== item.code))); };
  const indices = useMemo(() => data?.indices.map((item) => ({ ...item, series: fullSeries[item.code] ?? item.series })) ?? [], [data, fullSeries]);
  useEffect(() => { if (!data || !start) return; data.indices.filter((item) => selected.includes(item.code) && item.series[0]?.date > start).forEach(loadFull); }, [data, selected, start]); // ponytail: eight fixed indices make this linear scan clearer than a cache abstraction.
  useEffect(() => { if (!ready) return; const prefs = { selected, start, log: comparisonLog, date: lockedDate }; localStorage.setItem("sector-dashboard-prefs", JSON.stringify(prefs)); const query = new URLSearchParams(); if (selected.length) query.set("selected", selected.join(",")); if (start) query.set("start", start); if (comparisonLog) query.set("log", "1"); if (lockedDate) query.set("date", lockedDate); history.replaceState(null, "", `${location.pathname}?${query}`); }, [comparisonLog, lockedDate, ready, selected, start]);
  if (error) return <main className="center-state"><strong>板块数据暂不可用</strong><span>{error}</span></main>;
  if (!data || !analysis) return <main className="center-state"><span className="pulse" /><strong>正在载入持仓板块指数</strong></main>;
  const ranked = [...indices].sort((a,b) => (b.summary.daily_return_pct ?? -999) - (a.summary.daily_return_pct ?? -999)), cached = indices.filter((item) => qualityOf(item).status === "cached").length, noAmount = indices.filter((item) => !qualityOf(item).has_amount).length;
  const chooseRange = (range: "今年" | "1年" | "3年" | "5年" | "全部") => { if (range === "全部") return setStart(data.requested_start_date); const date = new Date(`${data.latest_a_share_date}T00:00:00`); if (range === "今年") date.setMonth(0,1); else date.setFullYear(date.getFullYear() - Number(range[0])); setStart(date.toISOString().slice(0,10)); };
  return <main><header className="topbar"><div className="brand"><span className="brand-mark">板</span><div><strong>SECTOR SIGNAL DESK</strong><small>HOLDINGS EXPOSURE MONITOR</small></div></div><div className="market-stamp"><span className="live-dot" />A股指数截至 {data.latest_a_share_date}<span>·</span>每日收盘后更新</div><nav className="top-actions"><a className="download" href={assetPath("/")}>NASDAQ 监控</a><a className="download" href={assetPath("/data/sector_indices_daily.csv")} download>下载 CSV</a></nav></header>
    <div className="sector-dashboard">
      <section className="sector-intro panel"><div><span className="eyebrow">PORTFOLIO SECTOR MAP · 8 CORE BENCHMARKS</span><h1>持仓板块指数</h1><p>芯片上游、通信、AI、电池、有色、机器人、黄金与美国大盘；NASDAQ 在独立页面监控。</p></div><div className="sector-leader"><span>今日领涨</span><strong>{ranked[0].name}</strong><b className={tone(ranked[0].summary.daily_return_pct)}>{pct(ranked[0].summary.daily_return_pct)}</b></div></section>
      <section className="quality-strip panel"><span><small>数据生成</small><strong>{new Date(data.generated_at).toLocaleString("zh-CN", { hour12: false })}</strong></span><span><small>官方 / 缓存</small><strong>{indices.length-cached} / {cached}</strong></span><span><small>交易日历</small><strong>{[...new Set(indices.map((i) => qualityOf(i).calendar))].join(" · ")}</strong></span><span><small>缺少成交额口径</small><strong>{noAmount} 个</strong></span></section>
      {lockedDate && <div className="date-lock panel"><span>全图已锁定 <strong>{lockedDate}</strong>，拖动任意图并松手可改日期</span><button onClick={() => setLockedDate(null)}>解除锁定</button></div>}
      <section className="sector-grid">{indices.map((item) => { const quality = qualityOf(item); return <article className="sector-card panel" key={item.code}><div className="sector-card-head"><div><span>{item.code} · {item.category}</span><h2>{item.name}</h2></div><b className={tone(item.summary.daily_return_pct)}>{pct(item.summary.daily_return_pct)}</b></div><MiniChart index={item} lockedDate={lockedDate} onLockDate={setLockedDate} onNeedFull={() => loadFull(item)} loading={loading.includes(item.code)} /><div className="sector-stats"><span>收盘<strong>{fmt(item.summary.close)}</strong></span><span>20日涨跌<strong className={tone(item.summary.returns.twenty_days)}>{pct(item.summary.returns.twenty_days)}</strong></span><span>当日净额<strong className={tone(item.summary.estimated_net_flow_billion)}>{flowText(item.summary.estimated_net_flow_billion)}</strong></span><span>5日 / 20日净额<strong className={tone(item.summary.estimated_net_flow_20_billion)}>{fmt(item.summary.estimated_net_flow_5_billion)} / {fmt(item.summary.estimated_net_flow_20_billion)} 亿</strong><small>方向占比 {pct(item.summary.money_flow_ratio_5_pct)} / {pct(item.summary.money_flow_ratio_20_pct)} · 可信度 {pct(item.summary.flow_confidence_pct)}</small></span></div><small className="sector-source"><i className={quality.status} />{quality.status === "official" ? "官方当次数据" : "缓存回退"} · {quality.calendar} · {item.source} · 截至 {item.latest_date}{!quality.has_amount ? " · 无同口径成交额" : ""}</small></article>; })}</section>
      <section className="comparison-panel panel"><div className="section-head"><div><span className="eyebrow">NORMALIZED COMPARISON</span><h2>多指数归一化比较</h2></div><div className="comparison-controls"><div className="range-buttons">{(["今年","1年","3年","5年","全部"] as const).map((label) => <button key={label} onClick={() => chooseRange(label)}>{label}</button>)}</div><button className={comparisonLog ? "active" : ""} onClick={() => setComparisonLog((v) => !v)}>对数收益</button><label className="date-control">起点<input type="date" min={data.requested_start_date} max={data.latest_a_share_date} value={start} onChange={(e) => setStart(e.target.value)} /></label></div></div><div className="index-picker">{indices.map((item) => <label key={item.code}><input type="checkbox" checked={selected.includes(item.code)} onChange={() => setSelected((v) => v.includes(item.code) ? v.filter((code) => code !== item.code) : [...v,item.code])} /><i style={{ background: item.color }} />{item.name}</label>)}</div><ComparisonChart indices={indices} selected={selected} requestedStart={start} logScale={comparisonLog} lockedDate={lockedDate} onLockDate={setLockedDate} /></section>
      <section className="ai-panel panel sector-ai"><div className="section-head"><div><span className="eyebrow">DAILY SYNTHESIS · THINK MODE</span><h2>当日跨板块分析</h2></div><span className={`source-chip ${analysis.status === "fallback" ? "fallback" : ""}`}>{analysis.source}{analysis.model ? ` · ${analysis.model}` : ""}</span></div>{analysis.error && <p className="ai-error">DeepSeek 暂未生效：{analysis.error}</p>}{analysis.sections ? <div className="analysis-sections">{Object.entries(sectionLabels).map(([key,label]) => <article key={key}><small>{label}</small><p>{analysis.sections?.[key]}</p></article>)}</div> : <div className="ai-copy">{analysis.text}</div>}{analysis.evidence?.length ? <div className="evidence-strip"><strong>数据证据（后端校验）</strong>{analysis.evidence.map((item,i) => <span key={`${item.code}-${item.metric}-${i}`}>{item.name} · {item.label}<b>{typeof item.value === "number" ? fmt(item.value) : item.value ?? "—"}</b></span>)}</div> : null}<p className="disclaimer">{analysis.disclaimer} “资金方向”是量价位置估算，不是交易所披露的真实净流入。</p></section>
      <section className="table-panel panel"><div className="section-head"><div><span className="eyebrow">DAILY RANKING</span><h2>当日强弱与资金方向估算</h2></div><span className="row-count">{indices.length} 个核心指数</span></div><div className="table-scroll"><table><thead><tr><th>指数</th><th>当日</th><th>5日</th><th>20日</th><th>60日</th><th>今年</th><th>当日流入 / 流出</th><th>当日净额 / 占比</th><th>5日净额 / 占比</th><th>20日净额 / 占比</th><th>可信度</th><th>趋势</th></tr></thead><tbody>{ranked.map((item) => <tr key={item.code}><td>{item.name}<small>{item.code}</small></td><td className={tone(item.summary.daily_return_pct)}>{pct(item.summary.daily_return_pct)}</td><td className={tone(item.summary.returns.five_days)}>{pct(item.summary.returns.five_days)}</td><td className={tone(item.summary.returns.twenty_days)}>{pct(item.summary.returns.twenty_days)}</td><td className={tone(item.summary.returns.sixty_days)}>{pct(item.summary.returns.sixty_days)}</td><td className={tone(item.summary.returns.ytd)}>{pct(item.summary.returns.ytd)}</td><td>{fmt(item.summary.estimated_inflow_billion)} / {fmt(item.summary.estimated_outflow_billion)} 亿</td><td className={tone(item.summary.estimated_net_flow_billion)}>{fmt(item.summary.estimated_net_flow_billion)}亿 / {pct(item.summary.money_flow_ratio_pct)}</td><td className={tone(item.summary.estimated_net_flow_5_billion)}>{fmt(item.summary.estimated_net_flow_5_billion)}亿 / {pct(item.summary.money_flow_ratio_5_pct)}</td><td className={tone(item.summary.estimated_net_flow_20_billion)}>{fmt(item.summary.estimated_net_flow_20_billion)}亿 / {pct(item.summary.money_flow_ratio_20_pct)}</td><td>{pct(item.summary.flow_confidence_pct)}</td><td>{item.summary.trend}</td></tr>)}</tbody></table></div><p className="method-note">方向占比 = (2×收盘−最高−最低) ÷ (最高−最低)；净额 = 成交额×方向占比。5/20日为逐日估算净额之和；可信度按成交额相对20日均值封顶至100%，只表示当日样本活跃度。</p></section>
    </div><footer>SECTOR SIGNAL DESK <span>·</span> OFFICIAL INDEX DATA <span>·</span> NOT INVESTMENT ADVICE</footer></main>;
}
