"use client";

import { useEffect, useRef, useState } from "react";
import FundChart, { type FundPoint } from "../components/FundChart";

type Holding={stock_id:string;code:string;name:string;weight_pct:number|null;shares_10k:number|null;market_value_10k:number|null;stock_path?:string|null};
type Fund={code:string;name:string;sector_code:string;sector_name:string;series:FundPoint[];summary:{latest_date:string;nav:number;daily_return_pct:number|null};holdings_report_date:string|null;holdings:Holding[];asset_allocation:Record<string,string|number|null>;analysis:{sections:Record<string,string>}};
type News={date:string;title:string;category:string;source:string;url?:string};
type Stock={stock_id:string;code:string;name:string;summary:{latest_date:string|null;close:number|null;daily_return_pct:number|null;return_5d_pct:number|null;return_20d_pct:number|null;volume_ratio20:number|null};financial:{report_date:string;report_type:string;revenue_billion:number|null;revenue_yoy_pct:number|null;net_profit_billion:number|null;net_profit_yoy_pct:number|null;roe_pct:number|null}|null;news:News[];analysis:{sections:Record<string,string>;source_indices:number[];source?:string};series:FundPoint[]};
const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
const assetPath=(path:string)=>`${basePath}${path}${path.endsWith(".json")?`?v=${Date.now()}`:""}`;
const fmt=(value:number|null|undefined,digits=2)=>value==null?"—":value.toLocaleString("zh-CN",{maximumFractionDigits:digits});
const pct=(value:number|null|undefined)=>value==null?"—":`${value>=0?"+":""}${value.toFixed(2)}%`;
const tone=(value:number|null|undefined)=>value==null||value===0?"neutral":value>0?"positive":"negative";

function StockCard({holding,lockedDate,onLockDate}:{holding:Holding;lockedDate:string|null;onLockDate:(date:string)=>void}){
  const root=useRef<HTMLElement>(null),[stock,setStock]=useState<Stock|null>(null),[showNews,setShowNews]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const element=root.current;if(!element||!holding.stock_path)return;const observer=new IntersectionObserver((entries)=>{if(!entries[0].isIntersecting)return;observer.disconnect();fetch(assetPath(holding.stock_path!)).then((response)=>response.json()).then(setStock).catch(()=>setError("行情载入失败"));},{rootMargin:"500px"});observer.observe(element);return()=>observer.disconnect();},[holding.stock_path]);
  return <article className="stock-card panel" ref={root}><div className="stock-rank"><b>{pct(holding.weight_pct)}</b><small>占基金净资产</small></div><div className="sector-card-head"><div><span>{holding.code} · 公开披露持仓</span><h2>{holding.name}</h2></div>{stock&&<b className={tone(stock.summary.daily_return_pct)}>{pct(stock.summary.daily_return_pct)}</b>}</div>{stock?.series?.length?<FundChart series={stock.series} color="#38bdf8" lockedDate={lockedDate} onLockDate={onLockDate} storageKey={stock.stock_id}/>:<div className="stock-loading">{error||(stock?"该市场历史行情暂不可用":"滚动到此处后载入行情…")}</div>}<div className="sector-stats fund-stats"><span>最新价格<strong>{fmt(stock?.summary.close)}</strong></span><span>近5日<strong className={tone(stock?.summary.return_5d_pct)}>{pct(stock?.summary.return_5d_pct)}</strong></span><span>近20日<strong className={tone(stock?.summary.return_20d_pct)}>{pct(stock?.summary.return_20d_pct)}</strong></span><span>持仓市值<strong>{fmt(holding.market_value_10k)} 万元</strong></span></div><div className="fund-actions"><button disabled={!stock} onClick={()=>setShowNews((value)=>!value)}>{stock?.analysis.source??"AI/规则"} · 新闻、公告与财报</button><span>披露份额 {fmt(holding.shares_10k)} 万股</span></div>{showNews&&stock&&<div className="stock-intel"><div className="analysis-sections compact">{Object.entries(stock.analysis.sections).map(([key,value])=><article key={key}><small>{({event:"重要事件",financial:"财务信息",reaction:"市场反应",risks:"风险边界",watch:"后续观察"} as Record<string,string>)[key]??key}</small><p>{value}</p></article>)}</div>{stock.financial&&<div className="financial-strip"><span>报告期<strong>{stock.financial.report_type}<br/>{stock.financial.report_date}</strong></span><span>营收<strong>{fmt(stock.financial.revenue_billion)}亿元<br/><i className={tone(stock.financial.revenue_yoy_pct)}>{pct(stock.financial.revenue_yoy_pct)}</i></strong></span><span>归母净利润<strong>{fmt(stock.financial.net_profit_billion)}亿元<br/><i className={tone(stock.financial.net_profit_yoy_pct)}>{pct(stock.financial.net_profit_yoy_pct)}</i></strong></span><span>ROE<strong>{pct(stock.financial.roe_pct)}</strong></span></div>}<div className="news-list">{stock.news.length?stock.news.map((item,index)=><a key={`${item.date}-${index}`} href={item.url} target="_blank" rel="noreferrer"><time>{item.date}</time><span>{item.title}<small>{item.category} · {item.source}</small></span></a>):<p>近期没有取得新的可核验公告或新闻。</p>}</div></div>}</article>;
}

export default function FundPage(){
  const [fund,setFund]=useState<Fund|null>(null),[lockedDate,setLockedDate]=useState<string|null>(null),[error,setError]=useState("");
  useEffect(()=>{const code=new URLSearchParams(location.search).get("code");if(!code)return setError("缺少基金代码");fetch(assetPath(`/data/funds/${code}.json`)).then((response)=>{if(!response.ok)throw new Error("基金详情尚未生成");return response.json();}).then(setFund).catch((reason)=>setError(reason.message));},[]);
  if(error)return <main className="center-state"><strong>基金详情暂不可用</strong><span>{error}</span></main>;
  if(!fund)return <main className="center-state"><span className="pulse"/><strong>正在载入基金与持仓</strong></main>;
  const allocation=fund.asset_allocation;
  return <main><header className="topbar"><div className="brand"><span className="brand-mark">仓</span><div><strong>FUND HOLDINGS</strong><small>DISCLOSED TOP POSITIONS</small></div></div><nav className="top-actions"><a className="download" href={assetPath(`/funds.html?sector=${fund.sector_code}`)}>返回基金列表</a></nav></header><div className="sector-dashboard fund-dashboard">
    <section className="sector-intro panel"><div><span className="eyebrow">{fund.code} · {fund.sector_name}</span><h1>{fund.name}</h1><p>以下按最新公开定期报告的持仓占基金净资产比例排列，不代表基金当前实时仓位。ETF 联接基金的直接股票仓位可能很低。</p></div><div className="sector-leader"><span>最新净值</span><strong>{fmt(fund.summary.nav,4)}</strong><b className={tone(fund.summary.daily_return_pct)}>{pct(fund.summary.daily_return_pct)}</b></div></section>
    {lockedDate&&<div className="date-lock panel"><span>所有曲线锁定 <strong>{lockedDate}</strong></span><button onClick={()=>setLockedDate(null)}>解除锁定</button></div>}
    <section className="comparison-panel panel"><div className="section-head"><div><span className="eyebrow">FUND NAV</span><h2>基金净值曲线</h2></div><span className="source-chip">截至 {fund.summary.latest_date}</span></div><FundChart series={fund.series} color="#22d3ee" lockedDate={lockedDate} onLockDate={setLockedDate} storageKey={fund.code}/></section>
    <section className="quality-strip panel"><span><small>持仓报告期</small><strong>{fund.holdings_report_date??"暂无"}</strong></span><span><small>股票占净比</small><strong>{fmt(allocation["股票占净比"] as number)}%</strong></span><span><small>债券占净比</small><strong>{fmt(allocation["债券占净比"] as number)}%</strong></span><span><small>现金占净比</small><strong>{fmt(allocation["现金占净比"] as number)}%</strong></span></section>
    <section className="holdings-head panel"><div><span className="eyebrow">DISCLOSED HOLDINGS</span><h2>公开披露重仓股</h2></div><strong>{fund.holdings.length} 只 · 按占净值比例排序</strong></section>
    <section className="stock-stack">{fund.holdings.map((holding)=><StockCard key={holding.stock_id} holding={holding} lockedDate={lockedDate} onLockDate={setLockedDate}/>)}</section>
  </div><footer>DISCLOSED HOLDINGS ARE DELAYED · SOURCE LINKS PROVIDED · NOT INVESTMENT ADVICE</footer></main>;
}
